import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary - Expanded to cover entire website
const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        "nav.home": "Home",
        "nav.browseIssues": "Browse Issues",
        "nav.issues": "Issues",
        "nav.report": "Report Issue",
        "nav.leaderboard": "Leaderboard",
        "nav.wallet": "Wallet",
        "nav.about": "About",
        "nav.myIssues": "My Issues",
        "nav.notifications": "Notifications",
        "nav.login": "Login",
        "nav.logout": "Logout",
        "nav.signIn": "Sign In",
        "nav.signUp": "Sign Up",
        "nav.analytics": "Analytics",
        "nav.settings": "Settings",
        "nav.walletRewards": "Wallet & Rewards",

        // Common
        "common.submit": "Submit",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.back": "Back",
        "common.backToHome": "Back to Home",
        "common.loading": "Loading...",
        "common.search": "Search",
        "common.filter": "Filter",
        "common.close": "Close",
        "common.continue": "Continue",
        "common.next": "Next",
        "common.previous": "Previous",
        "common.yes": "Yes",
        "common.no": "No",
        "common.online": "Online",
        "common.points": "Points",
        "common.viewAll": "View All",

        // Hero
        "hero.verified": "Government Verified Platform",
        "hero.title1": "Your Voice,",
        "hero.title2": "Your City's Future",
        "hero.subtitle": "Report civic issues, track resolutions, and hold authorities accountable. Together, we build transparent and responsive governance.",
        "hero.reportBtn": "Report an Issue",
        "hero.browseBtn": "Browse Issues",
        "hero.stats.resolved": "Issues Resolved",
        "hero.stats.citizens": "Active Citizens",
        "hero.stats.funds": "Funds Utilized",

        // Categories
        "categories.title": "Report Issues by Category",
        "categories.subtitle": "Select the category that best matches your civic concern for faster routing and resolution.",
        "categories.viewAll": "View all categories",
        "categories.road.name": "Road & Transportation",
        "categories.road.desc": "Potholes, damaged roads, broken footpaths, and public transport issues",
        "categories.water.name": "Water Supply & Drainage",
        "categories.water.desc": "Water shortage, contamination, leakage, and drainage blockages",
        "categories.electricity.name": "Electricity & Streetlights",
        "categories.electricity.desc": "Power outages, faulty streetlights, and electrical hazards",
        "categories.sanitation.name": "Sanitation & Waste",
        "categories.sanitation.desc": "Garbage collection, waste dumping, and cleanliness issues",
        "categories.safety.name": "Public Safety & Crime",
        "categories.safety.desc": "Safety concerns, suspicious activities, and crime reporting",
        "categories.traffic.name": "Traffic & Signals",
        "categories.traffic.desc": "Traffic congestion, signal malfunctions, and road safety",
        "categories.parks.name": "Parks & Public Spaces",
        "categories.parks.desc": "Maintenance of parks, playgrounds, and community areas",
        "categories.government.name": "Government Offices",
        "categories.government.desc": "Issues with government office services and facilities",
        "categories.toilets.name": "Public Toilets & Hygiene",
        "categories.toilets.desc": "Public toilet maintenance and hygiene concerns",
        "categories.environment.name": "Environmental Issues",
        "categories.environment.desc": "Pollution, illegal tree cutting, and water body concerns",
        "categories.animal.name": "Animal Welfare",
        "categories.animal.desc": "Stray animals, animal cruelty, and wildlife concerns",
        "categories.other.name": "Other Issues",
        "categories.other.desc": "Issues not covered by other categories",

        // Footer
        "footer.description": "Empowering citizens to build better communities through transparent civic engagement.",
        "footer.quickLinks": "Quick Links",
        "footer.issueCategories": "Issue Categories",
        "footer.contactUs": "Contact Us",
        "footer.copyright": "© 2025 Nagrik Samadhan. Government of India Initiative.",
        "footer.privacy": "Privacy Policy",
        "footer.terms": "Terms of Service",
        "footer.accessibility": "Accessibility",
        "footer.aboutUs": "About Us",

        // How It Works
        "howItWorks.title": "How It Works",
        "howItWorks.subtitle": "A transparent, step-by-step process ensuring accountability at every stage",
        "howItWorks.step1.title": "Report Issue",
        "howItWorks.step1.desc": "Submit civic issues with photos, location, and details. Your privacy is protected with automatic face and plate blurring.",
        "howItWorks.step2.title": "Government Review",
        "howItWorks.step2.desc": "State authorities review and route issues to the appropriate Municipal Corporation for verification.",
        "howItWorks.step3.title": "Cost Approval",
        "howItWorks.step3.desc": "Transparent cost estimation in ₹ INR with public visibility. Community funding available for approved issues.",
        "howItWorks.step4.title": "Resolution & Proof",
        "howItWorks.step4.desc": "Authorities resolve issues and submit proof. Complete audit trail ensures accountability.",
        "howItWorks.step5.title": "Review & Reward",
        "howItWorks.step5.desc": "Verify resolution and earn rewards. Top contributors receive monthly cash prizes!",

        // Features
        "features.title": "Built for Accountability",
        "features.subtitle": "Every feature designed to ensure transparency, prevent corruption, and empower citizens",
        "features.f1.title": "Privacy Protected",
        "features.f1.desc": "Automatic face and vehicle plate blurring ensures citizen privacy while maintaining transparency.",
        "features.f2.title": "Full Transparency",
        "features.f2.desc": "Every action, approval, and expense is publicly visible with immutable audit trails.",
        "features.f3.title": "Community Funding",
        "features.f3.desc": "Support local issues with donations. All funds held in escrow with automatic refunds if unused.",
        "features.f4.title": "Financial Clarity",
        "features.f4.desc": "All costs in ₹ INR with clear breakdown of government and community contributions.",
        "features.f5.title": "Real-time Updates",
        "features.f5.desc": "Get instant notifications on issue status, SLA breaches, and resolution updates.",
        "features.f6.title": "Rewards Program",
        "features.f6.desc": "Earn points for verified reports. Monthly leaderboard with cash rewards for top contributors.",

        // CTA
        "cta.title": "Ready to Make a Difference?",
        "cta.subtitle": "Join thousands of citizens working together to build better communities. Report issues, track progress, and hold authorities accountable.",
        "cta.reportBtn": "Report an Issue",
        "cta.createAccount": "Create Account",

        // Auth
        "auth.welcome": "Welcome Back",
        "auth.login": "Login",
        "auth.signup": "Sign Up",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.phone": "Phone Number",
        "auth.otp": "OTP",
        "auth.sendOtp": "Send OTP",
        "auth.verifyOtp": "Verify OTP & Login",
        "auth.verifyOtpSignup": "Verify & Create Account",
        "auth.aadhaar": "Aadhaar Number",
        "auth.verifyAadhaar": "Verify Aadhaar",
        "auth.googleLogin": "Continue with Google",
        "auth.googleSignup": "Sign up with Google",
        "auth.createAccount": "Create Account",
        "auth.forgotPassword": "Forgot password?",
        "auth.loginEmail": "Login with Email",
        "auth.signupPhone": "Sign up with Phone",
        "auth.orContinueWith": "Or continue with",
        "auth.orUsingEmail": "Or using email",
        "auth.orSignupWith": "Or sign up with",
        "auth.enterPhone": "Enter 10-digit number",
        "auth.enterOtp": "Enter OTP",
        "auth.editNumber": "Edit Number",
        "auth.createAccountDesc": "Sign up to report issues and participate",
        "auth.loginDesc": "Login to track your reported issues and earn rewards",

        // Report Issue
        "report.title": "Report a Civic Issue",
        "report.category": "Category",
        "report.selectCategory": "Select issue category",
        "report.issueTitle": "Title",
        "report.issueDetails": "Issue Details",
        "report.description": "Description",
        "report.urgency": "Urgency",
        "report.urgencyLow": "LOW",
        "report.urgencyMedium": "MEDIUM",
        "report.urgencyHigh": "HIGH",
        "report.location": "Location",
        "report.addressAutoFilled": "Address (auto-filled from map)",
        "report.pinLocation": "Pin Location on Map",
        "report.pinLocationDesc": "Click or drag marker to select exact location",
        "report.evidence": "Evidence",
        "report.submit": "Submit Issue",
        "report.submitting": "Submitting...",
        "report.privacy": "Uploaded media is processed to protect identities",
        "report.autoBlur": "Faces & number plates are auto-blurred",
        "report.dropPhotos": "Drop photos or videos here, or click to browse",
        "report.supportsFormats": "Supports JPG, PNG, MP4",
        "report.filesAdded": "file(s) added",
        "report.video": "Video",
        "report.selected": "Selected",

        // Issues
        "issues.all": "All Issues",
        "issues.browse": "Browse Issues",
        "issues.status": "Status",
        "issues.reported": "Reported",
        "issues.inProgress": "In Progress",
        "issues.resolved": "Resolved",
        "issues.rejected": "Rejected",

        // Analytics
        "analytics.title": "Analytics Dashboard",
        "analytics.overview": "Overview",
        "analytics.totalIssues": "Total Issues",
        "analytics.resolved": "Resolved",
        "analytics.pending": "Pending",
        "analytics.inProgress": "In Progress",
        "analytics.byCategory": "Issues by Category",
        "analytics.byStatus": "Issues by Status",
        "analytics.timeline": "Timeline",
        "analytics.comprehensiveOverview": "Comprehensive overview of your reported issues and their status",
        "analytics.statusDistribution": "Distribution of issues by current status",
        "analytics.resolutionRate": "Resolution Rate",
        "analytics.percentageResolved": "Percentage of resolved issues",
        "analytics.outOf": "out of",
        "analytics.issuesResolved": "issues resolved",
        "analytics.categoryBreakdown": "Number of issues reported in each category",
        "analytics.last7Days": "Issues reported over the last 7 days",
        "analytics.noData": "No data available",

        // Chatbot
        "chatbot.title": "Support Assistant",
        "chatbot.placeholder": "Type your question...",
        "chatbot.welcome": "Hello! How can I help you today?",

        // Fraud Alert
        "fraud.title": "Fraud Alert",
        "fraud.duplicate": "Duplicate Image Detected",
        "fraud.message": "This image has already been uploaded. Please use a different image.",
        "fraud.warning": "Uploading duplicate images may result in account suspension.",

        // User Menu
        "user.myIssues": "My Issues",
        "user.analytics": "Analytics",
        "user.wallet": "Wallet & Rewards",
        "user.settings": "Settings",
        "user.signOut": "Sign Out",

        // Aadhaar Verification
        "aadhaar.verificationComplete": "Verification Complete",
        "aadhaar.verifyTitle": "Verify Aadhaar",
        "aadhaar.enter12Digit": "Enter your 12-digit Aadhaar number for verification",
        "aadhaar.enterOtpDesc": "Enter the OTP sent to your registered mobile number",
        "aadhaar.successDesc": "Your Aadhaar has been successfully verified",
        "aadhaar.verificationSuccessful": "Verification Successful!",
        "aadhaar.canAccessFeatures": "You can now access all features of the platform",
        "aadhaar.sendingOtp": "Sending OTP...",
        "aadhaar.verifying": "Verifying...",
        "aadhaar.verify": "Verify",
        "aadhaar.privacyNotice": "Privacy Notice:",
        "aadhaar.privacyEncrypted": "Your Aadhaar details are encrypted and secure",
        "aadhaar.privacyOnlyStatus": "Only verification status is stored",
        "aadhaar.privacyNotShared": "Aadhaar number is NOT shared with authorities",
        "aadhaar.privacyFraudPrevention": "Used only to prevent fraud and spam",

        // My Issues
        "myIssues.signinTitle": "Please Sign In",
        "myIssues.signinDesc": "You need to be logged in to view your reported issues.",
        "myIssues.title": "My Issues History",
        "myIssues.subtitle": "Track the status of issues you have reported",
        "myIssues.totalReported": "Total Reported",
        "myIssues.loading": "Loading your history...",
        "myIssues.noIssuesTitle": "No issues reported yet",
        "myIssues.noIssuesDesc": "You haven't reported any civic issues yet.",
        "common.recently": "Recently",

        // Wallet
        "wallet.currentBalance": "Current Balance",
        "wallet.availableForWithdrawal": "Available for withdrawal",
        "wallet.rewardPoints": "Reward Points",
        "wallet.thisWeek": "this week",
        "wallet.lifetimeEarnings": "Lifetime Earnings",
        "wallet.totalEarningsDesc": "Total earnings from rewards",
        "wallet.manageFunds": "Manage Funds",
        "wallet.withdraw": "Withdraw",
        "wallet.addFunds": "Add Funds",
        "wallet.bankTransfer": "Bank Transfer",
        "wallet.amountLabel": "Amount (₹)",
        "wallet.amountPlaceholder": "Enter amount",
        "wallet.upiId": "UPI ID",
        "wallet.accountNumber": "Account Number",
        "wallet.withdrawMoney": "Withdraw Money",
        "wallet.simulationNotice": "This is a simulation. Adding funds will increase your virtual wallet balance immediately.",
        "wallet.paymentMethod": "Payment Method",
        "wallet.card": "Card",
        "wallet.rewardsProgram": "Rewards Program",
        "wallet.verifiedReport": "Verified Issue Report",
        "wallet.communityVerification": "Community Verification",
        "wallet.topMonthly": "Top 10 Monthly Rank",
        "wallet.cash": "Cash",
        "wallet.recentActivity": "Recent Activity",
        "wallet.earnedPoints": "Earned Points",
        "wallet.contribution": "Contribution",
        "wallet.transactionHistory": "Transaction History",
        "wallet.insufficientBalance": "Insufficient balance",
        "wallet.invalidAmount": "Please enter a valid amount",

        // Leaderboard
        "leaderboard.title": "Top Contributors",
        "leaderboard.subtitle": "Citizens driving real change by reporting and resolving civic issues",
        "leaderboard.fullRankings": "Full Rankings",
        "leaderboard.reported": "reported",
        "leaderboard.resolved": "resolved",
        "leaderboard.monthlyRewards": "Monthly Rewards",
        "leaderboard.loading": "Loading leaderboard...",
        "leaderboard.user": "User",

        // About
        "about.tagline": "Government Civic Platform",
        "about.titlePrefix": "About",
        "about.desc1": "A unified digital grievance redressal and civic issue management platform designed to promote transparency, accountability, and citizen participation in public service delivery.",
        "about.desc2": "Nagrik Samadhan has been developed as part of a modern e-Governance initiative to bridge the gap between citizens and civic authorities. The platform enables citizens to report civic infrastructure issues, track progress, and ensure time-bound resolution through a transparent and accountable digital system.",
        "about.vision": "Vision",
        "about.visionDesc": "To establish a transparent, accountable, and responsive governance ecosystem where technology empowers citizens and strengthens public trust in civic administration.",
        "about.mission": "Mission",
        "about.mission1": "Provide a single-window digital platform for civic issue reporting",
        "about.mission2": "Enhance transparency and accountability in grievance redressal",
        "about.mission3": "Enable data-driven decision-making for civic authorities",
        "about.mission4": "Encourage active citizen participation in governance",
        "about.feature1": "Institutional Transparency",
        "about.feature1Desc": "Public visibility of reported issues and resolution timelines.",
        "about.feature2": "Citizen Participation",
        "about.feature2Desc": "Empowers citizens to actively engage in governance.",
        "about.feature3": "Data Security",
        "about.feature3Desc": "Secure handling of data following government-grade standards.",

        // Issue Detail & Funding
        "issues.notFound": "Issue Not Found",
        "issues.backToIssues": "Back to Issues",
        "issues.issue": "Issue",
        "issues.statusTimeline": "Status Timeline",
        "issues.timelineNote": "Timeline subject to weather conditions and material availability.",
        "funding.helpSolve": "Help Solve This Issue",
        "funding.desc": "Community contribution accelerates resolution. Funds are held in escrow until completion.",
        "funding.fundBtn": "Fund This Issue",
        "funding.contributeTitle": "Contribute to Resolution",
        "funding.paymentSecurity": "Secure payment gateway. 100% refundable if issue not resolved.",
        "funding.amountLabel": "Contribution Amount (₹)",
        "funding.amountPlaceholder": "Enter amount (e.g. 500)",
        "funding.scanUpi": "Scan with any UPI App",
        "funding.enterUpi": "Or enter UPI ID",
        "funding.payContribute": "Pay & Contribute",
        "funding.cardNumber": "Card Number",
        "funding.expiry": "Expiry",
        "funding.cvv": "CVV",
        "funding.paySecurely": "Pay Securely",
        "funding.selectBank": "Select Bank",
        "funding.proceed": "Proceed",
        "funding.status": "Funding Status",
        "funding.totalRequired": "Total Required",
        "funding.raised": "Raised",
        "funding.govtGrant": "Govt Grant",
        "funding.community": "Community",
        "funding.recentContributors": "Recent Contributors",
        "funding.noContributions": "No community contributions yet.",
        "funding.expectedTimeline": "Expected Timeline",
        "funding.estimatedStart": "Estimated Start",
        "funding.estimatedCompletion": "Estimated Completion",
        "funding.anonymous": "Anonymous Citizen",
        "common.share": "Share",
        "common.citizen": "Citizen",
        "common.paySuccess": "Payment Successful! Thank you for your contribution.",
        "common.redirectBank": "Redirecting to Bank...",

        // Timeline Steps
        "timeline.reported": "Reported",
        "timeline.reportedDesc": "Issue has been reported by citizen",
        "timeline.stateReviewed": "State Reviewed",
        "timeline.stateReviewedDesc": "Reviewed by State Government authority",
        "timeline.municipalVerified": "Municipal Verified",
        "timeline.municipalVerifiedDesc": "Verified by Municipal Corporation",
        "timeline.costApproved": "Cost Approved",
        "timeline.costApprovedDesc": "Resolution cost and timeline approved",
        "timeline.funded": "Funded",
        "timeline.fundedDesc": "Required funding has been secured",
        "timeline.inProgress": "In Progress",
        "timeline.inProgressDesc": "Resolution work is underway",
        "timeline.resolved": "Resolved",
        "timeline.resolvedDesc": "Issue has been resolved and verified",

        // Notifications
        "notifications.markAllRead": "Mark all as read",
        "notifications.noNotifications": "No notifications yet",

        // Recent Issues
        "recentIssues.title": "Recent Issues",
        "recentIssues.subtitle": "Track civic issues being reported and resolved",
        "issues.viewAll": "View All Issues",
        "issues.noReports": "No issues reported yet.",
        "common.loadingRecent": "Loading recent issues...",
    },
    hi: {
        // Navigation
        "nav.home": "होम",
        "nav.browseIssues": "समस्याएं ब्राउज़ करें",
        "nav.issues": "समस्याएं",
        "nav.report": "समस्या रिपोर्ट करें",
        "nav.leaderboard": "लीडरबोर्ड",
        "nav.wallet": "वॉलेट",
        "nav.about": "हमारे बारे में",
        "nav.myIssues": "मेरी समस्याएं",
        "nav.notifications": "सूचनाएं",
        "nav.login": "लॉगिन",
        "nav.logout": "लॉगआउट",
        "nav.signIn": "साइन इन",
        "nav.signUp": "साइन अप",
        "nav.analytics": "विश्लेषण",
        "nav.settings": "सेटिंग्स",
        "nav.walletRewards": "वॉलेट और इनाम",

        // Common
        "common.submit": "जमा करें",
        "common.cancel": "रद्द करें",
        "common.save": "सहेजें",
        "common.delete": "हटाएं",
        "common.edit": "संपादित करें",
        "common.back": "वापस",
        "common.backToHome": "होम पर वापस जाएं",
        "common.loading": "लोड हो रहा है...",
        "common.search": "खोजें",
        "common.filter": "फ़िल्टर",
        "common.close": "बंद करें",
        "common.continue": "जारी रखें",
        "common.next": "अगला",
        "common.previous": "पिछला",
        "common.yes": "हाँ",
        "common.no": "नहीं",
        "common.online": "ऑनलाइन",
        "common.points": "अंक",
        "common.viewAll": "सभी देखें",

        // Hero
        "hero.verified": "सरकारी सत्यापित मंच",
        "hero.title1": "आपकी आवाज़,",
        "hero.title2": "आपके शहर का भविष्य",
        "hero.subtitle": "नागरिक समस्याओं की रिपोर्ट करें, समाधानों को ट्रैक करें और अधिकारियों को जवाबदेह ठहराएं। साथ मिलकर, हम पारदर्शी और उत्तरदायी शासन का निर्माण करते हैं।",
        "hero.reportBtn": "एक समस्या रिपोर्ट करें",
        "hero.browseBtn": "समस्याएं ब्राउज़ करें",
        "hero.stats.resolved": "हल की गई समस्याएं",
        "hero.stats.citizens": "सक्रिय नागरिक",
        "hero.stats.funds": "उपयोग की गई राशि",

        // Categories
        "categories.title": "श्रेणी के अनुसार समस्याओं की रिपोर्ट करें",
        "categories.subtitle": "तेजी से रूटिंग और समाधान के लिए अपनी नागरिक चिंता से सबसे अच्छी तरह मेल खाने वाली श्रेणी चुनें।",
        "categories.viewAll": "सभी श्रेणियां देखें",
        "categories.road.name": "सड़क और परिवहन",
        "categories.road.desc": "गड्ढे, क्षतिग्रस्त सड़कें, टूटे फुटपाथ और सार्वजनिक परिवहन के मुद्दे",
        "categories.water.name": "जल आपूर्ति और जल निकासी",
        "categories.water.desc": "पानी की कमी, संदूषण, रिसाव और जल निकासी अवरोध",
        "categories.electricity.name": "बिजली और स्ट्रीट लाइट",
        "categories.electricity.desc": "बिजली कटौती, खराब स्ट्रीट लाइट और बिजली के खतरे",
        "categories.sanitation.name": "स्वच्छता और अपशिष्ट",
        "categories.sanitation.desc": "कचरा संग्रह, कचरा डंपिंग और सफाई के मुद्दे",
        "categories.safety.name": "सार्वजनिक सुरक्षा और अपराध",
        "categories.safety.desc": "सुरक्षा चिंताएं, संदिग्ध गतिविधियां और अपराध की रिपोर्टिंग",
        "categories.traffic.name": "यातायात और सिग्नल",
        "categories.traffic.desc": "यातायात भीड़, सिग्नल की खराबी और सड़क सुरक्षा",
        "categories.parks.name": "पार्क और सार्वजनिक स्थान",
        "categories.parks.desc": "पार्क, खेल के मैदान और सामुदायिक क्षेत्रों का रखरखाव",
        "categories.government.name": "सरकारी कार्यालय",
        "categories.government.desc": "सरकारी कार्यालय सेवाओं और सुविधाओं के साथ मुद्दे",
        "categories.toilets.name": "सार्वजनिक शौचालय और स्वच्छता",
        "categories.toilets.desc": "सार्वजनिक शौचालय रखरखाव और स्वच्छता संबंधी चिंताएं",
        "categories.environment.name": "पर्यावरण संबंधी मुद्दे",
        "categories.environment.desc": "प्रदूषण, अवैध पेड़ कटाई और जल निकाय की चिंताएं",
        "categories.animal.name": "पशु कल्याण",
        "categories.animal.desc": "आवारा पशु, पशु क्रूरता और वन्यजीव चिंताएं",
        "categories.other.name": "अन्य मुद्दे",
        "categories.other.desc": "अन्य श्रेणियों में शामिल नहीं किए गए मुद्दे",

        // Footer
        "footer.description": "पारदर्शी नागरिक जुड़ाव के माध्यम से बेहतर समुदायों के निर्माण के लिए नागरिकों को सशक्त बनाना।",
        "footer.quickLinks": "त्वरित लिंक",
        "footer.issueCategories": "समस्या श्रेणियां",
        "footer.contactUs": "संपर्क करें",
        "footer.copyright": "© 2025 नागरिक समाधान। भारत सरकार की पहल।",
        "footer.privacy": "गोपनीयता नीति",
        "footer.terms": "सेवा की शर्तें",
        "footer.accessibility": "अभिगम्यता",
        "footer.aboutUs": "हमारे बारे में",

        // How It Works
        "howItWorks.title": "यह कैसे काम करता है",
        "howItWorks.subtitle": "एक पारदर्शी, चरण-दर-चरण प्रक्रिया जो हर स्तर पर जवाबदेही सुनिश्चित करती है",
        "howItWorks.step1.title": "समस्या रिपोर्ट करें",
        "howItWorks.step1.desc": "फोटो, स्थान और विवरण के साथ नागरिक समस्याएं जमा करें। आपकी गोपनीयता स्वचालित चेहरे और प्लेट धुंधला करने के साथ सुरक्षित है।",
        "howItWorks.step2.title": "सरकारी समीक्षा",
        "howItWorks.step2.desc": "राज्य अधिकारी समीक्षा करते हैं और सत्यापन के लिए उपयुक्त नगर निगम को समस्याएं भेजते हैं।",
        "howItWorks.step3.title": "लागत स्वीकृति",
        "howItWorks.step3.desc": "सार्वजनिक दृश्यता के साथ ₹ INR में पारदर्शी लागत अनुमान। अनुमोदित मुद्दों के लिए सामुदायिक वित्तपोषण उपलब्ध है।",
        "howItWorks.step4.title": "समाधान और प्रमाण",
        "howItWorks.step4.desc": "अधिकारी मुद्दों का समाधान करते हैं और प्रमाण जमा करते हैं। पूर्ण ऑडिट ट्रेल जवाबदेही सुनिश्चित करता है।",
        "howItWorks.step5.title": "समीक्षा और इनाम",
        "howItWorks.step5.desc": "समाधान सत्यापित करें और इनाम अर्जित करें। शीर्ष योगदानकर्ताओं को मासिक नकद पुरस्कार मिलते हैं!",

        // Features
        "features.title": "जवाबदेही के लिए निर्मित",
        "features.subtitle": "पारदर्शिता सुनिश्चित करने, भ्रष्टाचार रोकने और नागरिकों को सशक्त बनाने के लिए डिज़ाइन की गई हर विशेषता",
        "features.f1.title": "गोपनीयता सुरक्षित",
        "features.f1.desc": "स्वचालित चेहरे और वाहन प्लेट धुंधला करना पारदर्शिता बनाए रखते हुए नागरिक गोपनीयता सुनिश्चित करता है।",
        "features.f2.title": "पूर्ण पारदर्शिता",
        "features.f2.desc": "हर कार्रवाई, अनुमोदन और खर्च अपरिवर्तनीय ऑडिट ट्रेल के साथ सार्वजनिक रूप से दृश्यमान है।",
        "features.f3.title": "सामुदायिक वित्तपोषण",
        "features.f3.desc": "दान के साथ स्थानीय मुद्दों का समर्थन करें। सभी फंड एस्क्रो में रखे जाते हैं और अप्रयुक्त होने पर स्वचालित रिफंड दिया जाता है।",
        "features.f4.title": "वित्तीय स्पष्टता",
        "features.f4.desc": "सरकार और सामुदायिक योगदान के स्पष्ट विवरण के साथ ₹ INR में सभी लागतें।",
        "features.f5.title": "रीयल-टाइम अपडेट",
        "features.f5.desc": "समस्या की स्थिति, SLA उल्लंघन और समाधान अपडेट पर तुरंत सूचनाएं प्राप्त करें।",
        "features.f6.title": "इनाम कार्यक्रम",
        "features.f6.desc": "सत्यापित रिपोर्टों के लिए अंक अर्जित करें। शीर्ष योगदानकर्ताओं के लिए नकद पुरस्कारों के साथ मासिक लीडरबोर्ड।",

        // CTA
        "cta.title": "बदलाव लाने के लिए तैयार हैं?",
        "cta.subtitle": "बेहतर समुदायों के निर्माण के लिए मिलकर काम करने वाले हजारों नागरिकों से जुड़ें। समस्याओं की रिपोर्ट करें, प्रगति को ट्रैक करें और अधिकारियों को जवाबदेह ठहराएं।",
        "cta.reportBtn": "एक समस्या रिपोर्ट करें",
        "cta.createAccount": "खाता बनाएं",

        // Auth
        "auth.welcome": "वापसी पर स्वागत है",
        "auth.login": "लॉगिन",
        "auth.signup": "साइन अप",
        "auth.email": "ईमेल",
        "auth.password": "पासवर्ड",
        "auth.phone": "फोन नंबर",
        "auth.otp": "ओटीपी",
        "auth.sendOtp": "ओटीपी भेजें",
        "auth.verifyOtp": "ओटीपी सत्यापित करें और लॉगिन करें",
        "auth.verifyOtpSignup": "सत्यापित करें और खाता बनाएं",
        "auth.aadhaar": "आधार नंबर",
        "auth.verifyAadhaar": "आधार सत्यापित करें",
        "auth.googleLogin": "गूगल के साथ जारी रखें",
        "auth.googleSignup": "गूगल के साथ साइन अप करें",
        "auth.createAccount": "खाता बनाएं",
        "auth.forgotPassword": "पासवर्ड भूल गए?",
        "auth.loginEmail": "ईमेल के साथ लॉगिन करें",
        "auth.signupPhone": "फोन के साथ साइन अप करें",
        "auth.orContinueWith": "या जारी रखें",
        "auth.orUsingEmail": "या ईमेल का उपयोग करके",
        "auth.orSignupWith": "या साइन अप करें",
        "auth.enterPhone": "10 अंकों का नंबर दर्ज करें",
        "auth.enterOtp": "ओटीपी दर्ज करें",
        "auth.editNumber": "नंबर संपादित करें",
        "auth.createAccountDesc": "समस्याओं की रिपोर्ट करने और भाग लेने के लिए साइन अप करें",
        "auth.loginDesc": "अपनी रिपोर्ट की गई समस्याओं को ट्रैक करने और इनाम अर्जित करने के लिए लॉगिन करें",

        // Report Issue
        "report.title": "नागरिक समस्या रिपोर्ट करें",
        "report.category": "श्रेणी",
        "report.selectCategory": "समस्या श्रेणी चुनें",
        "report.issueTitle": "शीर्षक",
        "report.issueDetails": "समस्या विवरण",
        "report.description": "विवरण",
        "report.urgency": "तात्कालिकता",
        "report.urgencyLow": "कम",
        "report.urgencyMedium": "मध्यम",
        "report.urgencyHigh": "उच्च",
        "report.location": "स्थान",
        "report.addressAutoFilled": "पता (मानचित्र से स्वतः भरा गया)",
        "report.pinLocation": "मानचित्र पर स्थान पिन करें",
        "report.pinLocationDesc": "सटीक स्थान चुनने के लिए क्लिक करें या मार्कर खींचें",
        "report.evidence": "सबूत",
        "report.submit": "समस्या जमा करें",
        "report.submitting": "जमा हो रहा है...",
        "report.privacy": "अपलोड किए गए मीडिया को पहचान की सुरक्षा के लिए संसाधित किया जाता है",
        "report.autoBlur": "चेहरे और नंबर प्लेट स्वचालित रूप से धुंधली हो जाती हैं",
        "report.dropPhotos": "फ़ोटो या वीडियो यहां छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
        "report.supportsFormats": "JPG, PNG, MP4 समर्थित है",
        "report.filesAdded": "फ़ाइल(एं) जोड़ी गईं",
        "report.video": "वीडियो",
        "report.selected": "चयनित",

        // Issues
        "issues.all": "सभी समस्याएं",
        "issues.browse": "समस्याएं ब्राउज़ करें",
        "issues.status": "स्थिति",
        "issues.reported": "रिपोर्ट की गई",
        "issues.inProgress": "प्रगति में",
        "issues.resolved": "हल हो गया",
        "issues.rejected": "अस्वीकृत",

        // Analytics
        "analytics.title": "विश्लेषण डैशबोर्ड",
        "analytics.overview": "अवलोकन",
        "analytics.totalIssues": "कुल समस्याएं",
        "analytics.resolved": "हल हो गया",
        "analytics.pending": "लंबित",
        "analytics.inProgress": "प्रगति में",
        "analytics.byCategory": "श्रेणी के अनुसार समस्याएं",
        "analytics.byStatus": "स्थिति के अनुसार समस्याएं",
        "analytics.timeline": "समयरेखा",
        "analytics.comprehensiveOverview": "आपकी रिपोर्ट की गई समस्याओं और उनकी स्थिति का व्यापक अवलोकन",
        "analytics.statusDistribution": "वर्तमान स्थिति के अनुसार समस्याओं का वितरण",
        "analytics.resolutionRate": "समाधान दर",
        "analytics.percentageResolved": "हल की गई समस्याओं का प्रतिशत",
        "analytics.outOf": "में से",
        "analytics.issuesResolved": "समस्याएं हल हुईं",
        "analytics.categoryBreakdown": "प्रत्येक श्रेणी में रिपोर्ट की गई समस्याओं की संख्या",
        "analytics.last7Days": "पिछले 7 दिनों में रिपोर्ट की गई समस्याएं",
        "analytics.noData": "कोई डेटा उपलब्ध नहीं है",

        // Chatbot
        "chatbot.title": "सहायता सहायक",
        "chatbot.placeholder": "अपना प्रश्न टाइप करें...",
        "chatbot.welcome": "नमस्ते! मैं आज आपकी कैसे मदद कर सकता हूं?",

        // Fraud Alert
        "fraud.title": "धोखाधड़ी चेतावनी",
        "fraud.duplicate": "डुप्लिकेट छवि का पता चला",
        "fraud.message": "यह छवि पहले से अपलोड की जा चुकी है। कृपया एक अलग छवि का उपयोग करें।",
        "fraud.warning": "डुप्लिकेट छवियां अपलोड करने से खाता निलंबन हो सकता है।",

        // User Menu
        "user.myIssues": "मेरी समस्याएं",
        "user.analytics": "विश्लेषण",
        "user.wallet": "वॉलेट और इनाम",
        "user.settings": "सेटिंग्स",
        "user.signOut": "साइन आउट",

        // Aadhaar Verification
        "aadhaar.verificationComplete": "सत्यापन पूर्ण",
        "aadhaar.verifyTitle": "आधार सत्यापित करें",
        "aadhaar.enter12Digit": "सत्यापन के लिए अपना 12 अंकों का आधार नंबर दर्ज करें",
        "aadhaar.enterOtpDesc": "अपने पंजीकृत मोबाइल नंबर पर भेजा गया ओटीपी दर्ज करें",
        "aadhaar.successDesc": "आपका आधार सफलतापूर्वक सत्यापित हो गया है",
        "aadhaar.verificationSuccessful": "सत्यापन सफल!",
        "aadhaar.canAccessFeatures": "अब आप प्लेटफ़ॉर्म की सभी सुविधाओं तक पहुंच सकते हैं",
        "aadhaar.sendingOtp": "ओटीपी भेजा जा रहा है...",
        "aadhaar.verifying": "सत्यापित हो रहा है...",
        "aadhaar.verify": "सत्यापित करें",
        "aadhaar.privacyNotice": "गोपनीयता सूचना:",
        "aadhaar.privacyEncrypted": "आपका आधार विवरण एन्क्रिप्टेड और सुरक्षित है",
        "aadhaar.privacyOnlyStatus": "केवल सत्यापन स्थिति संग्रहीत है",
        "aadhaar.privacyNotShared": "आधार नंबर अधिकारियों के साथ साझा नहीं किया गया है",
        "aadhaar.privacyFraudPrevention": "केवल धोखाधड़ी और स्पैम को रोकने के लिए उपयोग किया जाता है",

        // My Issues
        "myIssues.signinTitle": "कृपया साइन इन करें",
        "myIssues.signinDesc": "अपनी रिपोर्ट की गई समस्याओं को देखने के लिए आपको लॉग इन करना होगा।",
        "myIssues.title": "मेरी समस्याओं का इतिहास",
        "myIssues.subtitle": "आपके द्वारा रिपोर्ट की गई समस्याओं की स्थिति को ट्रैक करें",
        "myIssues.totalReported": "कुल रिपोर्ट की गई",
        "myIssues.loading": "आपका इतिहास लोड हो रहा है...",
        "myIssues.noIssuesTitle": "अभी तक कोई समस्या रिपोर्ट नहीं की गई",
        "myIssues.noIssuesDesc": "आपने अभी तक कोई नागरिक समस्या रिपोर्ट नहीं की है।",
        "common.recently": "हाल ही में",

        // Wallet
        "wallet.currentBalance": "वर्तमान शेष राशि",
        "wallet.availableForWithdrawal": "निकासी के लिए उपलब्ध",
        "wallet.rewardPoints": "इनाम अंक",
        "wallet.thisWeek": "इस सप्ताह",
        "wallet.lifetimeEarnings": "जीवनकाल की कमाई",
        "wallet.totalEarningsDesc": "इनामों से कुल कमाई",
        "wallet.manageFunds": "फंड प्रबंधित करें",
        "wallet.withdraw": "निकालें",
        "wallet.addFunds": "फंड जोड़ें",
        "wallet.bankTransfer": "बैंक ट्रांसफर",
        "wallet.amountLabel": "राशि (₹)",
        "wallet.amountPlaceholder": "राशि दर्ज करें",
        "wallet.upiId": "यूआईडी",
        "wallet.accountNumber": "खाता संख्या",
        "wallet.withdrawMoney": "पैसे निकालें",
        "wallet.simulationNotice": "यह एक सिमुलेशन है। फंड जोड़ने से आपके वर्चुअल वॉलेट की शेष राशि तुरंत बढ़ जाएगी।",
        "wallet.paymentMethod": "भुगतान विधि",
        "wallet.card": "कार्ड",
        "wallet.rewardsProgram": "इनाम कार्यक्रम",
        "wallet.verifiedReport": "सत्यापित समस्या रिपोर्ट",
        "wallet.communityVerification": "सामुदायिक सत्यापन",
        "wallet.topMonthly": "शीर्ष 10 मासिक रैंक",
        "wallet.cash": "नकद",
        "wallet.recentActivity": "हाल की गतिविधि",
        "wallet.earnedPoints": "अर्जित अंक",
        "wallet.contribution": "योगदान",
        "wallet.transactionHistory": "लेनदेन का इतिहास",
        "wallet.insufficientBalance": "अपर्याप्त शेष राशि",
        "wallet.invalidAmount": "कृपया एक मान्य राशि दर्ज करें",

        // Leaderboard
        "leaderboard.title": "शीर्ष योगदानकर्ता",
        "leaderboard.subtitle": "नागरिक समस्याओं की रिपोर्ट करके और उनका समाधान करके वास्तविक बदलाव ला रहे हैं",
        "leaderboard.fullRankings": "पूर्ण रैंकिंग",
        "leaderboard.reported": "रिपोर्ट की गई",
        "leaderboard.resolved": "हल की गई",
        "leaderboard.monthlyRewards": "मासिक पुरस्कार",
        "leaderboard.loading": "लीडरबोर्ड लोड हो रहा है...",
        "leaderboard.user": "उपयोगकर्ता",

        // About
        "about.tagline": "सरकारी नागरिक मंच",
        "about.titlePrefix": "हमारे बारे में",
        "about.desc1": "एक एकीकृत डिजिटल शिकायत निवारण और नागरिक समस्या प्रबंधन मंच जिसे सार्वजनिक सेवा वितरण में पारदर्शिता, जवाबदेही और नागरिक भागीदारी को बढ़ावा देने के लिए डिज़ाइन किया गया है।",
        "about.desc2": "नागरिक समाधान को नागरिकों और नागरिक अधिकारियों के बीच की खाई को पाटने के लिए एक आधुनिक ई-गवर्नेंस पहल के हिस्से के रूप में विकसित किया गया है। यह मंच नागरिकों को नागरिक बुनियादी ढांचे के मुद्दों की रिपोर्ट करने, प्रगति को ट्रैक करने और पारदर्शी और जवाबदेह डिजिटल प्रणाली के माध्यम से समयबद्ध समाधान सुनिश्चित करने में सक्षम बनाता है।",
        "about.vision": "दृष्टिकोण",
        "about.visionDesc": "एक पारदर्शी, जवाबदेह और उत्तरदायी शासन पारिस्थितिकी तंत्र स्थापित करना जहां तकनीक नागरिकों को सशक्त बनाती है और नागरिक प्रशासन में सार्वजनिक विश्वास को मजबूत करती है।",
        "about.mission": "लक्ष्य",
        "about.mission1": "नागरिक समस्या रिपोर्टिंग के लिए सिंगल-विंडो डिजिटल प्लेटफॉर्म प्रदान करें",
        "about.mission2": "शिकायत निवारण में पारदर्शिता और जवाबदेही बढ़ाएं",
        "about.mission3": "नागरिक अधिकारियों के लिए डेटा-संचालित निर्णय लेने में सक्षम बनाएं",
        "about.mission4": "शासन में सक्रिय नागरिक भागीदारी को प्रोत्साहित करें",
        "about.feature1": "संस्थागत पारदर्शिता",
        "about.feature1Desc": "रिपोर्ट की गई समस्याओं और समाधान समयसीमा की सार्वजनिक दृश्यता।",
        "about.feature2": "नागरिक भागीदारी",
        "about.feature2Desc": "नागरिकों को शासन में सक्रिय रूप से शामिल होने के लिए सशक्त बनाता है।",
        "about.feature3": "डेटा सुरक्षा",
        "about.feature3Desc": "सरकारी स्तर के मानकों के अनुसार डेटा की सुरक्षित हैंडलिंग।",

        // Issue Detail & Funding
        "issues.notFound": "समस्या नहीं मिली",
        "issues.backToIssues": "समस्याओं पर वापस जाएं",
        "issues.issue": "समस्या",
        "issues.statusTimeline": "स्थिति समयरेखा",
        "issues.timelineNote": "समयरेखा मौसम की स्थिति और सामग्री की उपलब्धता के अधीन है।",
        "funding.helpSolve": "इस समस्या को हल करने में सहायता करें",
        "funding.desc": "सामुदायिक योगदान समाधान में तेजी लाता है। पूरा होने तक फंड एस्क्रो में रखे जाते हैं।",
        "funding.fundBtn": "इस समस्या को फंड करें",
        "funding.contributeTitle": "समाधान में योगदान दें",
        "funding.paymentSecurity": "सुरक्षित भुगतान गेटवे। समस्या हल न होने पर 100% वापसी योग्य।",
        "funding.amountLabel": "योगदान राशि (₹)",
        "funding.amountPlaceholder": "राशि दर्ज करें (जैसे 500)",
        "funding.scanUpi": "किसी भी UPI ऐप से स्कैन करें",
        "funding.enterUpi": "या UPI ID दर्ज करें",
        "funding.payContribute": "भुगतान करें और योगदान दें",
        "funding.cardNumber": "कार्ड नंबर",
        "funding.expiry": "समाप्ति",
        "funding.cvv": "सीवीवी",
        "funding.paySecurely": "सुरक्षित भुगतान करें",
        "funding.selectBank": "बैंक चुनें",
        "funding.proceed": "आगे बढ़ें",
        "funding.status": "फंडिंग स्थिति",
        "funding.totalRequired": "कुल आवश्यक",
        "funding.raised": "जुटाया गया",
        "funding.govtGrant": "सरकारी अनुदान",
        "funding.community": "समुदाय",
        "funding.recentContributors": "हाल के योगदानकर्ता",
        "funding.noContributions": "अभी तक कोई सामुदायिक योगदान नहीं है।",
        "funding.expectedTimeline": "अपेक्षित समयरेखा",
        "funding.estimatedStart": "अनुमानित शुरुआत",
        "funding.estimatedCompletion": "अनुमानित पूर्णता",
        "funding.anonymous": "अनाम नागरिक",
        "common.share": "साझा करें",
        "common.citizen": "नागरिक",
        "common.paySuccess": "भुगतान सफल! आपके योगदान के लिए धन्यवाद।",
        "common.redirectBank": "बैंक को निर्देशित किया जा रहा है...",

        // Timeline Steps
        "timeline.reported": "रिपोर्ट की गई",
        "timeline.reportedDesc": "नागरिक द्वारा समस्या की रिपोर्ट की गई है",
        "timeline.stateReviewed": "राज्य द्वारा समीक्षा की गई",
        "timeline.stateReviewedDesc": "राज्य सरकार के प्राधिकरण द्वारा समीक्षा की गई",
        "timeline.municipalVerified": "नगरपालिका द्वारा सत्यापित",
        "timeline.municipalVerifiedDesc": "नगर निगम द्वारा सत्यापित",
        "timeline.costApproved": "लागत अनुमोदित",
        "timeline.costApprovedDesc": "समाधान लागत और समयरेखा अनुमोदित",
        "timeline.funded": "वित्तपोषित",
        "timeline.fundedDesc": "आवश्यक वित्त पोषण सुरक्षित कर लिया गया है",
        "timeline.inProgress": "प्रगति में",
        "timeline.inProgressDesc": "समाधान कार्य चल रहा है",
        "timeline.resolved": "हल हो गई",
        "timeline.resolvedDesc": "समस्या का समाधान और सत्यापन हो गया है",

        // Notifications
        "notifications.markAllRead": "सभी पढ़े गए के रूप में चिह्नित करें",
        "notifications.noNotifications": "अभी तक कोई सूचना नहीं है",

        // Recent Issues
        "recentIssues.title": "हाल की समस्याएं",
        "recentIssues.subtitle": "रिपोर्ट की जा रही और हल की जा रही नागरिक समस्याओं को ट्रैक करें",
        "issues.viewAll": "सभी समस्याएं देखें",
        "issues.noReports": "अभी तक कोई समस्या रिपोर्ट नहीं की गई है।",
        "common.loadingRecent": "हाल की समस्याएं लोड हो रही हैं...",
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        // Load language from localStorage
        const saved = localStorage.getItem("language") as Language;
        if (saved && (saved === "en" || saved === "hi")) {
            setLanguageState(saved);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within LanguageProvider");
    }
    return context;
}
